import { School, Stage } from "@/lib/types";

export const schools: School[] = [
  // ─── Kindergartens (kg-001 to kg-025) ────────────────────────────

  {
    id: "kg-001",
    nameZh: "樂思幼稚園",
    nameEn: "Joy Think Kindergarten",
    stage: "kg",
    district: "九龍城",
    schoolType: "非牟利",
    sessionType: "全日",
    schoolNet: null,
    band: null,
    addressZh: "九龍城嘉林邊道18號地下至2樓",
    phone: "2345 6789",
    website: "https://www.joythink.edu.hk",
    tuitionFee: 2800,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-001",
        schoolId: "kg-001",
        grade: "K1",
        status: "available",
        count: 8,
        updatedAt: "2026-03-18T10:00:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-002",
        schoolId: "kg-001",
        grade: "K2",
        status: "available",
        count: 3,
        updatedAt: "2026-03-18T10:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-002",
    nameZh: "聖保祿幼稚園",
    nameEn: "St. Paul's Kindergarten",
    stage: "kg",
    district: "灣仔",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "灣仔堅尼地道9-13號",
    phone: "2572 3911",
    website: "https://www.stpaulkg.edu.hk",
    tuitionFee: 0,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-003",
        schoolId: "kg-002",
        grade: "K1",
        status: "full",
        count: 0,
        updatedAt: "2026-03-18T09:30:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-003",
    nameZh: "培正幼稚園",
    nameEn: "Pui Ching Kindergarten",
    stage: "kg",
    district: "九龍城",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "九龍城窩打老道80號",
    phone: "2714 2258",
    website: "https://www.pckg.edu.hk",
    tuitionFee: 1500,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-004",
        schoolId: "kg-003",
        grade: "K1",
        status: "waiting",
        count: null,
        updatedAt: "2026-03-17T14:00:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-005",
        schoolId: "kg-003",
        grade: "K2",
        status: "available",
        count: 5,
        updatedAt: "2026-03-17T14:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-004",
    nameZh: "維多利亞幼稚園",
    nameEn: "Victoria Kindergarten",
    stage: "kg",
    district: "中西區",
    schoolType: "私立",
    sessionType: "全日",
    schoolNet: null,
    band: null,
    addressZh: "中環堅道100號地下",
    phone: "2523 7325",
    website: "https://www.victoria.edu.hk",
    tuitionFee: 8500,
    isSchemeParticipant: false,
    vacancies: [
      {
        id: "vac-006",
        schoolId: "kg-004",
        grade: "K1",
        status: "available",
        count: 4,
        updatedAt: "2026-03-18T11:00:00+08:00",
        isStale: false,
        source: "manual",
      },
      {
        id: "vac-007",
        schoolId: "kg-004",
        grade: "K2",
        status: "full",
        count: 0,
        updatedAt: "2026-03-18T11:00:00+08:00",
        isStale: false,
        source: "manual",
      },
      {
        id: "vac-008",
        schoolId: "kg-004",
        grade: "K3",
        status: "available",
        count: 2,
        updatedAt: "2026-03-18T11:00:00+08:00",
        isStale: false,
        source: "manual",
      },
    ],
  },
  {
    id: "kg-005",
    nameZh: "東華三院李黃慶祥紀念幼稚園",
    nameEn: "TWGHs Lee Wong Hing Cheung Memorial Kindergarten",
    stage: "kg",
    district: "觀塘",
    schoolType: "非牟利",
    sessionType: "全日及半日",
    schoolNet: null,
    band: null,
    addressZh: "觀塘翠屏道17號翠屏邨翠桃樓地下",
    phone: "2727 8318",
    website: "https://www.twghkg.edu.hk",
    tuitionFee: 0,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-009",
        schoolId: "kg-005",
        grade: "K1",
        status: "available",
        count: 12,
        updatedAt: "2026-03-17T16:30:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-010",
        schoolId: "kg-005",
        grade: "K2",
        status: "available",
        count: 6,
        updatedAt: "2026-03-17T16:30:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-006",
    nameZh: "聖公會青山聖彼得堂幼稚園",
    nameEn: "S.K.H. Castle Peak St. Peter's Church Kindergarten",
    stage: "kg",
    district: "屯門",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "屯門青山公路青山灣段393號",
    phone: "2450 7722",
    website: "https://www.skhcpkg.edu.hk",
    tuitionFee: 980,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-011",
        schoolId: "kg-006",
        grade: "K1",
        status: "available",
        count: 15,
        updatedAt: "2026-03-16T09:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-007",
    nameZh: "保良局蔡繼有幼稚園",
    nameEn: "PLK Choi Kai Yau Kindergarten",
    stage: "kg",
    district: "深水埗",
    schoolType: "非牟利",
    sessionType: "全日",
    schoolNet: null,
    band: null,
    addressZh: "深水埗廣利道3號",
    phone: "2386 0341",
    website: "https://www.plkckykg.edu.hk",
    tuitionFee: 0,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-012",
        schoolId: "kg-007",
        grade: "K1",
        status: "waiting",
        count: null,
        updatedAt: "2026-03-18T08:45:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-013",
        schoolId: "kg-007",
        grade: "K2",
        status: "waiting",
        count: null,
        updatedAt: "2026-03-18T08:45:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-008",
    nameZh: "啟思幼稚園（帝堡城）",
    nameEn: "Creative Kindergarten (Castello)",
    stage: "kg",
    district: "沙田",
    schoolType: "私立",
    sessionType: "全日及半日",
    schoolNet: null,
    band: null,
    addressZh: "沙田大涌橋路52號帝堡城地下",
    phone: "2648 9033",
    website: "https://www.creative.edu.hk",
    tuitionFee: 5800,
    isSchemeParticipant: false,
    vacancies: [
      {
        id: "vac-014",
        schoolId: "kg-008",
        grade: "K1",
        status: "available",
        count: 6,
        updatedAt: "2026-03-17T10:15:00+08:00",
        isStale: false,
        source: "kgp",
      },
    ],
  },
  {
    id: "kg-009",
    nameZh: "約克國際幼稚園",
    nameEn: "York International Kindergarten",
    stage: "kg",
    district: "油尖旺",
    schoolType: "國際學校",
    sessionType: "全日",
    schoolNet: null,
    band: null,
    addressZh: "尖沙咀廣東道30號新港中心1樓",
    phone: "2735 9268",
    website: "https://www.york.edu.hk",
    tuitionFee: 9200,
    isSchemeParticipant: false,
    vacancies: [
      {
        id: "vac-015",
        schoolId: "kg-009",
        grade: "K1",
        status: "available",
        count: 3,
        updatedAt: "2026-03-16T15:00:00+08:00",
        isStale: false,
        source: "manual",
      },
      {
        id: "vac-016",
        schoolId: "kg-009",
        grade: "N",
        status: "full",
        count: 0,
        updatedAt: "2026-03-16T15:00:00+08:00",
        isStale: false,
        source: "manual",
      },
    ],
  },
  {
    id: "kg-010",
    nameZh: "路德會呂君博幼稚園",
    nameEn: "Lui Kwan Pok Lutheran Kindergarten",
    stage: "kg",
    district: "東區",
    schoolType: "非牟利",
    sessionType: "半日（下午）",
    schoolNet: null,
    band: null,
    addressZh: "北角渣華道18號嘉和大廈2樓",
    phone: "2571 0341",
    website: "https://www.lkplkg.edu.hk",
    tuitionFee: 1200,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-017",
        schoolId: "kg-010",
        grade: "K1",
        status: "available",
        count: 10,
        updatedAt: "2026-03-18T12:00:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-018",
        schoolId: "kg-010",
        grade: "K3",
        status: "available",
        count: 7,
        updatedAt: "2026-03-18T12:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-011",
    nameZh: "荃灣浸信會幼稚園",
    nameEn: "Tsuen Wan Baptist Kindergarten",
    stage: "kg",
    district: "荃灣",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "荃灣大河道12號",
    phone: "2492 2338",
    website: "https://www.twbkg.edu.hk",
    tuitionFee: 0,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-019",
        schoolId: "kg-011",
        grade: "K1",
        status: "unknown",
        count: null,
        updatedAt: "2026-03-10T09:00:00+08:00",
        isStale: true,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-012",
    nameZh: "嘉德麗幼稚園",
    nameEn: "Catiline Kindergarten",
    stage: "kg",
    district: "沙田",
    schoolType: "非牟利",
    sessionType: "全日",
    schoolNet: null,
    band: null,
    addressZh: "沙田禾輋邨景和樓地下",
    phone: "2691 4885",
    website: "https://www.catiline.edu.hk",
    tuitionFee: 2200,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-020",
        schoolId: "kg-012",
        grade: "K1",
        status: "available",
        count: 9,
        updatedAt: "2026-03-17T11:30:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-021",
        schoolId: "kg-012",
        grade: "K2",
        status: "available",
        count: 4,
        updatedAt: "2026-03-17T11:30:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-022",
        schoolId: "kg-012",
        grade: "K3",
        status: "waiting",
        count: null,
        updatedAt: "2026-03-17T11:30:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-013",
    nameZh: "天主教聖瑪加利大幼稚園",
    nameEn: "St. Margaret Mary's Catholic Kindergarten",
    stage: "kg",
    district: "灣仔",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "跑馬地樂活道2A號",
    phone: "2576 4053",
    website: "https://www.smmckg.edu.hk",
    tuitionFee: 1800,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-023",
        schoolId: "kg-013",
        grade: "K1",
        status: "full",
        count: 0,
        updatedAt: "2026-03-18T09:00:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-024",
        schoolId: "kg-013",
        grade: "K2",
        status: "full",
        count: 0,
        updatedAt: "2026-03-18T09:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-014",
    nameZh: "明雅國際幼稚園",
    nameEn: "Mink International Pre-school",
    stage: "kg",
    district: "中西區",
    schoolType: "國際學校",
    sessionType: "全日",
    schoolNet: null,
    band: null,
    addressZh: "西營盤高街98號協康中心2樓",
    phone: "2547 0822",
    website: "https://www.minkintl.edu.hk",
    tuitionFee: 10500,
    isSchemeParticipant: false,
    vacancies: [
      {
        id: "vac-025",
        schoolId: "kg-014",
        grade: "N",
        status: "available",
        count: 5,
        updatedAt: "2026-03-15T14:00:00+08:00",
        isStale: false,
        source: "manual",
      },
      {
        id: "vac-026",
        schoolId: "kg-014",
        grade: "K1",
        status: "available",
        count: 2,
        updatedAt: "2026-03-15T14:00:00+08:00",
        isStale: false,
        source: "manual",
      },
    ],
  },
  {
    id: "kg-015",
    nameZh: "深水埗德貞幼稚園",
    nameEn: "Shamshuipo Tak Ching Kindergarten",
    stage: "kg",
    district: "深水埗",
    schoolType: "非牟利",
    sessionType: "全日及半日",
    schoolNet: null,
    band: null,
    addressZh: "深水埗元州街162號",
    phone: "2360 0381",
    website: "https://www.takckg.edu.hk",
    tuitionFee: 0,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-027",
        schoolId: "kg-015",
        grade: "K1",
        status: "available",
        count: 14,
        updatedAt: "2026-03-18T13:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-016",
    nameZh: "觀塘循道幼稚園",
    nameEn: "Kwun Tong Methodist Kindergarten",
    stage: "kg",
    district: "觀塘",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "觀塘瑞和街71號瑞和大廈3樓",
    phone: "2341 2932",
    website: "https://www.ktmkg.edu.hk",
    tuitionFee: 1050,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-028",
        schoolId: "kg-016",
        grade: "K1",
        status: "waiting",
        count: null,
        updatedAt: "2026-03-18T10:30:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-029",
        schoolId: "kg-016",
        grade: "K2",
        status: "available",
        count: 2,
        updatedAt: "2026-03-18T10:30:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-017",
    nameZh: "東華三院方譚遠良幼兒園",
    nameEn: "TWGHs Fong Tam Yuen Leung Nursery School",
    stage: "kg",
    district: "沙田",
    schoolType: "非牟利",
    sessionType: "全日",
    schoolNet: null,
    band: null,
    addressZh: "沙田瀝源邨榮瑞樓103-112號地下",
    phone: "2692 2886",
    website: "https://www.twghftyl.edu.hk",
    tuitionFee: 0,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-030",
        schoolId: "kg-017",
        grade: "K1",
        status: "available",
        count: 7,
        updatedAt: "2026-03-16T17:00:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-031",
        schoolId: "kg-017",
        grade: "K2",
        status: "available",
        count: 11,
        updatedAt: "2026-03-16T17:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-018",
    nameZh: "油蔴地天主教幼稚園",
    nameEn: "Yau Ma Tei Catholic Kindergarten",
    stage: "kg",
    district: "油尖旺",
    schoolType: "非牟利",
    sessionType: "半日（下午）",
    schoolNet: null,
    band: null,
    addressZh: "油尖旺東莞街41號",
    phone: "2384 3901",
    website: "https://www.ymtckg.edu.hk",
    tuitionFee: 1380,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-032",
        schoolId: "kg-018",
        grade: "K1",
        status: "available",
        count: 8,
        updatedAt: "2026-03-17T09:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-019",
    nameZh: "救世軍田家炳幼稚園",
    nameEn: "Salvation Army Tin Ka Ping Kindergarten",
    stage: "kg",
    district: "屯門",
    schoolType: "非牟利",
    sessionType: "全日",
    schoolNet: null,
    band: null,
    addressZh: "屯門良景邨良智樓地下",
    phone: "2462 5242",
    website: "https://www.satkpkg.edu.hk",
    tuitionFee: 0,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-033",
        schoolId: "kg-019",
        grade: "K1",
        status: "unknown",
        count: null,
        updatedAt: "2026-03-08T11:00:00+08:00",
        isStale: true,
        source: "kgp",
      },
      {
        id: "vac-034",
        schoolId: "kg-019",
        grade: "K2",
        status: "unknown",
        count: null,
        updatedAt: "2026-03-08T11:00:00+08:00",
        isStale: true,
        source: "kgp",
      },
    ],
  },
  {
    id: "kg-020",
    nameZh: "聖公會荊冕堂葛量洪幼稚園",
    nameEn: "S.K.H. Crown of Thorns Church Grantham Kindergarten",
    stage: "kg",
    district: "東區",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "北角雲景道51號",
    phone: "2578 0247",
    website: "https://www.skhctkg.edu.hk",
    tuitionFee: 890,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-035",
        schoolId: "kg-020",
        grade: "K1",
        status: "full",
        count: 0,
        updatedAt: "2026-03-18T08:00:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-036",
        schoolId: "kg-020",
        grade: "K2",
        status: "available",
        count: 3,
        updatedAt: "2026-03-18T08:00:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-037",
        schoolId: "kg-020",
        grade: "K3",
        status: "available",
        count: 5,
        updatedAt: "2026-03-18T08:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-021",
    nameZh: "崇真小學暨幼稚園",
    nameEn: "Tsung Tsin Primary School and Kindergarten",
    stage: "kg",
    district: "深水埗",
    schoolType: "非牟利",
    sessionType: "全日及半日",
    schoolNet: null,
    band: null,
    addressZh: "深水埗大埔道58號",
    phone: "2776 1423",
    website: "https://www.ttpskg.edu.hk",
    tuitionFee: 3200,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-038",
        schoolId: "kg-021",
        grade: "K1",
        status: "full",
        count: 0,
        updatedAt: "2026-03-17T15:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-022",
    nameZh: "荃灣商會朱昌幼稚園",
    nameEn: "Tsuen Wan Trade Association Chu Cheong Kindergarten",
    stage: "kg",
    district: "荃灣",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "荃灣海盛路3號",
    phone: "2414 0341",
    website: "https://www.twtacckg.edu.hk",
    tuitionFee: 1650,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-039",
        schoolId: "kg-022",
        grade: "K1",
        status: "available",
        count: 11,
        updatedAt: "2026-03-16T10:00:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-040",
        schoolId: "kg-022",
        grade: "K2",
        status: "available",
        count: 8,
        updatedAt: "2026-03-16T10:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-023",
    nameZh: "香港靈糧堂幼稚園",
    nameEn: "Hong Kong Ling Liang Church Kindergarten",
    stage: "kg",
    district: "九龍城",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "九龍城聯合道320號",
    phone: "2337 0361",
    website: "https://www.hkllckg.edu.hk",
    tuitionFee: 2100,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-041",
        schoolId: "kg-023",
        grade: "K1",
        status: "available",
        count: 5,
        updatedAt: "2026-03-18T14:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-024",
    nameZh: "寶血幼稚園",
    nameEn: "Precious Blood Kindergarten",
    stage: "kg",
    district: "油尖旺",
    schoolType: "非牟利",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "旺角界限街104-104A號",
    phone: "2392 4674",
    website: "https://www.pbkg.edu.hk",
    tuitionFee: 0,
    isSchemeParticipant: true,
    vacancies: [
      {
        id: "vac-042",
        schoolId: "kg-024",
        grade: "K1",
        status: "waiting",
        count: null,
        updatedAt: "2026-03-18T09:20:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-043",
        schoolId: "kg-024",
        grade: "K2",
        status: "available",
        count: 6,
        updatedAt: "2026-03-18T09:20:00+08:00",
        isStale: false,
        source: "edb",
      },
      {
        id: "vac-044",
        schoolId: "kg-024",
        grade: "K3",
        status: "available",
        count: 9,
        updatedAt: "2026-03-18T09:20:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "kg-025",
    nameZh: "民生書院幼稚園",
    nameEn: "Munsang College Kindergarten",
    stage: "kg",
    district: "九龍城",
    schoolType: "私立",
    sessionType: "半日（上午）",
    schoolNet: null,
    band: null,
    addressZh: "九龍城東寶庭道8號",
    phone: "2712 0027",
    website: "https://www.msc.edu.hk/kindergarten",
    tuitionFee: 6200,
    isSchemeParticipant: false,
    vacancies: [
      {
        id: "vac-045",
        schoolId: "kg-025",
        grade: "K1",
        status: "full",
        count: 0,
        updatedAt: "2026-03-12T16:00:00+08:00",
        isStale: true,
        source: "manual",
      },
    ],
  },

  // ─── Primary Schools (placeholders) ──────────────────────────────

  {
    id: "pri-001",
    nameZh: "九龍灣聖若翰天主教小學",
    nameEn: "Kowloon Bay St. John the Baptist Catholic Primary School",
    stage: "primary",
    district: "觀塘",
    schoolType: "資助",
    sessionType: null,
    schoolNet: "46",
    band: null,
    addressZh: "觀塘啟仁街6號",
    phone: "2789 0001",
    website: "https://www.kbsjb.edu.hk",
    tuitionFee: null,
    isSchemeParticipant: null,
    vacancies: [
      {
        id: "vac-046",
        schoolId: "pri-001",
        grade: "P1",
        status: "waiting",
        count: null,
        updatedAt: "2026-03-17T16:00:00+08:00",
        isStale: false,
        source: "manual",
      },
    ],
  },
  {
    id: "pri-002",
    nameZh: "沙田崇真學校",
    nameEn: "Shatin Tsung Tsin School",
    stage: "primary",
    district: "沙田",
    schoolType: "資助",
    sessionType: null,
    schoolNet: "88",
    band: null,
    addressZh: "沙田大圍積富街1號",
    phone: "2691 1027",
    website: "https://www.stts.edu.hk",
    tuitionFee: null,
    isSchemeParticipant: null,
    vacancies: [
      {
        id: "vac-047",
        schoolId: "pri-002",
        grade: "P1",
        status: "available",
        count: 5,
        updatedAt: "2026-03-16T12:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "pri-003",
    nameZh: "軒尼詩道官立小學",
    nameEn: "Hennessy Road Government Primary School",
    stage: "primary",
    district: "灣仔",
    schoolType: "官立",
    sessionType: null,
    schoolNet: "12",
    band: null,
    addressZh: "灣仔譚臣道169號",
    phone: "2572 6633",
    website: "https://www.hrgps.edu.hk",
    tuitionFee: null,
    isSchemeParticipant: null,
    vacancies: [
      {
        id: "vac-048",
        schoolId: "pri-003",
        grade: "P1",
        status: "full",
        count: 0,
        updatedAt: "2026-03-15T14:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },

  // ─── Secondary Schools (placeholders) ────────────────────────────

  {
    id: "sec-001",
    nameZh: "皇仁書院",
    nameEn: "Queen's College",
    stage: "secondary",
    district: "灣仔",
    schoolType: "官立",
    sessionType: null,
    schoolNet: null,
    band: "1",
    addressZh: "銅鑼灣高士威道120號",
    phone: "2576 8858",
    website: "https://www.qc.edu.hk",
    tuitionFee: null,
    isSchemeParticipant: null,
    vacancies: [
      {
        id: "vac-049",
        schoolId: "sec-001",
        grade: "S1",
        status: "full",
        count: 0,
        updatedAt: "2026-03-15T09:30:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
  {
    id: "sec-002",
    nameZh: "沙田培英中學",
    nameEn: "Shatin Pui Ying College",
    stage: "secondary",
    district: "沙田",
    schoolType: "資助",
    sessionType: null,
    schoolNet: null,
    band: "1",
    addressZh: "沙田禾輋邨豐順街9號",
    phone: "2691 7265",
    website: "https://www.pyc.edu.hk",
    tuitionFee: null,
    isSchemeParticipant: null,
    vacancies: [
      {
        id: "vac-050",
        schoolId: "sec-002",
        grade: "S1",
        status: "available",
        count: 3,
        updatedAt: "2026-03-14T10:00:00+08:00",
        isStale: false,
        source: "edb",
      },
    ],
  },
];

export const districtsByStage: Record<Stage, string[]> = {
  kg: [
    "九龍城",
    "沙田",
    "灣仔",
    "中西區",
    "觀塘",
    "深水埗",
    "油尖旺",
    "東區",
    "荃灣",
    "屯門",
  ],
  primary: ["觀塘", "沙田", "灣仔"],
  secondary: ["灣仔", "沙田"],
};
